name: news_appp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  alert_dialog: ^1.0.2
  alert_dialog_box: ^0.0.2
  bloc: ^8.1.4
  buttons_tabbar: ^1.3.13
  card_loading: ^0.3.2
  dartz: ^0.10.1
  dio: ^5.6.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.3.11
  get_it: ^7.7.0
  loading_animation_widget: ^1.2.1
  placeholder_utils: ^0.0.1
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets: -assets/images/splash.png
